- name: Install packages with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - stow
    - lazygit
    - eza
    - ripgrep
    - fish
    - starship
    - zoxide
    - mise
    - fzf
