- name: Install packages with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - lazygit
    - eza
    - ripgrep
    - fish
    - starship
    - zoxide
    - mise
    - fzf

- name: Install cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - google-chrome
    - docker
    - zed
